# Generated by Django 4.0.5 on 2022-06-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recomendation',
            field=models.CharField(choices=[('Must Watch', 'Must Watch'), ('Should Watch', 'Should Watch'), ('Avoid Watch', 'Avoid Watch'), ('No Opinion', 'No Opinion')], default='No Opinion', max_length=50),
        ),
    ]
